spring.application.name=FileStorageApp

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/FileStorageDb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

server.servlet.context-path=/api
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10KB
spring.servlet.multipart.max-request-size=10KB

#TODO: Use in dev profile, include dev profile
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=${SPRING_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

minio.url=${MINIO_URL:http://minio:9000}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-name=${MINIO_BUCKET_NAME}