spring.application.name=FileStorageApp

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/FileStorageDb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.data.redis.host=${SPRING_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
