spring.application.name=FileStorageApp

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/FileStorageDb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

server.servlet.context-path=/api
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100KB
spring.servlet.multipart.max-request-size=100KB

spring.data.redis.host=${SPRING_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

minio.url=${MINIO_URL:http://minio:9000}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-name=${MINIO_BUCKET_NAME}
minio.object-path-pattern=user-%d-files/%s
minio.presigned-url-ttl=900s

file.allowed-extensions=txt,pdf,jpg,jpeg,png,gif,zip,docx,xlsx
file.allowed-mime=text/plain,application/pdf,image/jpeg,image/png,application/zip