CREATE TABLE user_files
(
    id                bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           bigint                                  NOT NULL,
    object_key        VARCHAR(255)                            NOT NULL,
    size              bigint                                  NOT NULL DEFAULT 0,
    storage_item_type VARCHAR(255)                            NOT NULL,
    uploaded_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_files PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(20)                             NOT NULL,
    password VARCHAR(128)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE user_files
    ADD CONSTRAINT uc_user_files_object_key UNIQUE (object_key);